authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
name = "MyPrompt"
uuid = "b78a7444-de30-11e8-1888-c787cb831373"
version = "0.1.0"

[deps]
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[targets]
test = ["Test", "Jive"]

[compat]
julia = "1"
